version: '3.4'

services:
  nuget-server:
    image: sunside/simple-nuget-server
    environment:
      - NUGET_API_KEY=823281825
      - BASE_URL=/nuget
    volumes:
      - nuget-database:/var/www/db
      - nuget-packages:/var/www/packagefiles
    ports:
      - 56000:5000

volumes:
  nuget-database:  
  nuget-packages:
